Cleaned up and refactored serial solution.

diff --git a/Histogram/Serial/Test b/Histogram/Serial/Test
--- a/Histogram/Serial/Test
+++ b/Histogram/Serial/Test
@@ -12,6 +12,16 @@ mv hist.a hist.b hist.c result.out TestOutput/
 
 for file in hist.a hist.b hist.c result.out
 do
-    echo "---- Testing $file --------------------------------------------------"
     diff -q ./TestOutput/$file ../Tests/10000/$file
+    if [ $? -ne 0 ]
+    then
+        failed="yes"
+    fi
 done
+
+if [ $failed ]
+then
+    echo "Tests failed."
+else
+    echo "Tests passed."
+fi
